export interface Neighborhood {
  name: string;
  slug: string;
  region: string;
  /** One sentence that appears in the page hero — localizes the pitch. */
  tagline: string;
  /** 2–3 sentences of genuine local context for the page body. */
  body: string;
  /** Used in <meta description> — keep under 155 chars. */
  metaDescription: string;
  /** Nearby areas shown in the footer CTA for internal linking. */
  nearbyAreas: string[];
  /** Well-known local schools — shown in hero to signal local knowledge. */
  schools: string[];
}

export const neighborhoods: Neighborhood[] = [
  // ── San Fernando Valley ──────────────────────────────────────────────────
  {
    name: "Encino",
    slug: "encino-tutoring",
    region: "San Fernando Valley",
    tagline: "One-on-one tutoring for Encino families — patient, personalized, and built around your student.",
    body: "Encino students face real academic pressure — strong local schools set high expectations and the gap between struggling and thriving can grow fast. Whether your student needs to close a gap in math, build reading confidence, or prepare for the PSAT, SAT, or ACT, we meet them where they are and move at a pace that actually works.",
    metaDescription: "Private tutoring in Encino, CA — one-on-one sessions for K–12 and college students. Math, reading, science, SAT/ACT prep, ADHD-friendly. First call free.",
    nearbyAreas: ["Tarzana", "Sherman Oaks", "Woodland Hills"],
    schools: ["Crespi Carmelite High School", "Notre Dame High School", "Birmingham Community Charter", "Encino Charter Elementary", "Lanai Road Elementary"],
  },
  {
    name: "Tarzana",
    slug: "tarzana-tutoring",
    region: "San Fernando Valley",
    tagline: "Personalized tutoring in Tarzana — one tutor, every subject, every age.",
    body: "Tarzana families know how quickly a student can fall behind — and how hard it can be to find support that actually clicks. We work with students from kindergarten through college, covering everything from early reading and basic math to AP courses and college coursework, all in one-on-one sessions built around how your student learns.",
    metaDescription: "Private tutoring in Tarzana, CA — one-on-one academic support for K–12 and college. Math, reading, science, test prep, study skills. Free intro call.",
    nearbyAreas: ["Encino", "Woodland Hills", "Calabasas"],
    schools: ["El Camino Real Charter High School", "Portola Middle School", "Wilbur Charter", "Tarzana Elementary"],
  },
  {
    name: "Sherman Oaks",
    slug: "sherman-oaks-tutoring",
    region: "San Fernando Valley",
    tagline: "Tutoring in Sherman Oaks — real progress, built around your student's schedule and learning style.",
    body: "Sherman Oaks students range from elementary schoolers building foundational skills to high schoolers navigating honors and AP courses. We cover every stage — closing learning gaps, raising grades, building study habits, and prepping for standardized tests — with a calm, patient approach that keeps students from shutting down.",
    metaDescription: "Private tutoring in Sherman Oaks, CA — one-on-one sessions for all ages and subjects. Math, reading, SAT/ACT prep, ADHD-friendly support. Free call.",
    nearbyAreas: ["Encino", "Studio City", "Burbank"],
    schools: ["Notre Dame High School", "Walter Reed Middle School", "Millikan Middle School", "North Hollywood High School", "Kester Elementary"],
  },
  {
    name: "Studio City",
    slug: "studio-city-tutoring",
    region: "San Fernando Valley",
    tagline: "One-on-one tutoring in Studio City — for students who need more than a classroom can give.",
    body: "Studio City's schools are strong, which means expectations are high and falling behind can feel devastating fast. We work with students of all learning styles — including those with ADHD or executive-function gaps — to rebuild confidence, fill in the missing pieces, and turn a subject they dread into one they can actually handle.",
    metaDescription: "Private tutoring in Studio City, CA — patient, personalized 1-on-1 sessions for K–12 and college. Math, reading, science, test prep, ADHD support. Free call.",
    nearbyAreas: ["Sherman Oaks", "West Hollywood", "Beverly Hills"],
    schools: ["Harvard-Westlake School", "Campbell Hall School", "Carpenter Community Charter", "Walter Reed Middle School"],
  },
  {
    name: "Woodland Hills",
    slug: "woodland-hills-tutoring",
    region: "San Fernando Valley",
    tagline: "Tutoring in Woodland Hills — flexible, one-on-one sessions that work around busy family schedules.",
    body: "Woodland Hills families are juggling a lot — school, sports, activities, and work schedules that don't leave much room. We work around that. Whether your student needs weekly sessions or occasional targeted help before a big exam, we build a plan that fits the reality of your household and moves them forward consistently.",
    metaDescription: "Private tutoring in Woodland Hills, CA — flexible one-on-one sessions for K–12 and college. Math, reading, science, SAT/ACT prep. Free intro call.",
    nearbyAreas: ["Calabasas", "Tarzana", "Porter Ranch"],
    schools: ["El Camino Real Charter High School", "Taft Charter High School", "Hale Charter Academy", "Louisville High School"],
  },
  {
    name: "Calabasas",
    slug: "calabasas-tutoring",
    region: "San Fernando Valley",
    tagline: "One-on-one tutoring in Calabasas — high expectations met with patience and a real plan.",
    body: "Calabasas families invest seriously in their children's education — and they expect tutoring that matches that standard. Every student gets a custom plan, not a generic worksheet routine. We identify what's actually missing, rebuild from there, and equip students with skills that carry them beyond the next test and into every subject going forward.",
    metaDescription: "Private tutoring in Calabasas, CA — personalized one-on-one academic support for K–12 and college. Math, SAT/ACT prep, study skills. First call free.",
    nearbyAreas: ["Woodland Hills", "Agoura Hills", "Hidden Hills"],
    schools: ["Calabasas High School", "A.E. Wright Middle School", "Chaparral Elementary", "Viewpoint School"],
  },
  {
    name: "Porter Ranch",
    slug: "porter-ranch-tutoring",
    region: "San Fernando Valley",
    tagline: "One-on-one tutoring in Porter Ranch — structured, patient support for students from elementary through college.",
    body: "Porter Ranch families know the value of a head start. Whether your student needs to stay on track with a demanding honors schedule, close a gap before finals, or build the study habits that carry them into college, we create a plan that fits their specific situation and adjusts as they improve.",
    metaDescription: "Private tutoring in Porter Ranch, CA — one-on-one sessions for K–12 and college. Math, reading, science, SAT/ACT prep, study skills. Free intro call.",
    nearbyAreas: ["Northridge", "Woodland Hills", "Calabasas"],
    schools: ["Granada Hills Charter High School", "Porter Ranch Community School"],
  },
  {
    name: "Northridge",
    slug: "northridge-tutoring",
    region: "San Fernando Valley",
    tagline: "Tutoring in Northridge — from K–12 fundamentals to college-level coursework, one student at a time.",
    body: "Northridge students span a wide range — elementary readers building confidence, high schoolers pushing through AP classes, and college students navigating their first demanding courses. We meet every level with patience and a structured plan that targets exactly what's holding your student back.",
    metaDescription: "Private tutoring in Northridge, CA — one-on-one support for K–12 and college students. Math, reading, SAT/ACT prep, study skills. Free intro call.",
    nearbyAreas: ["Porter Ranch", "Encino", "Sherman Oaks"],
    schools: ["Granada Hills Charter High School", "Northridge Middle School", "CSUN"],
  },
  // ── Conejo Valley / West ─────────────────────────────────────────────────
  {
    name: "Westlake Village",
    slug: "westlake-village-tutoring",
    region: "Conejo Valley",
    tagline: "Tutoring in Westlake Village — high-caliber one-on-one academic support for students at every level.",
    body: "Westlake Village families set high academic expectations — and their students feel it. We help by identifying exactly what's missing, rebuilding from there, and giving students the skills and confidence to perform on their own. Weekly sessions, targeted exam prep, or something in between — we work around your schedule.",
    metaDescription: "Private tutoring in Westlake Village, CA — one-on-one support for K–12 and college. Math, reading, SAT/ACT prep, study skills. Free intro call.",
    nearbyAreas: ["Agoura Hills", "Calabasas", "Hidden Hills"],
    schools: ["Westlake High School", "White Oak Elementary", "Conejo Valley Unified schools"],
  },
  {
    name: "Agoura Hills",
    slug: "agoura-hills-tutoring",
    region: "Conejo Valley",
    tagline: "One-on-one tutoring in Agoura Hills — patient, personalized support for students who need more than their school offers.",
    body: "Agoura Hills students come from families who care deeply about academic success. We match that commitment with sessions built around your student's specific situation — not a generic program — that adjust week by week as they improve and as the demands of school evolve.",
    metaDescription: "Private tutoring in Agoura Hills, CA — one-on-one sessions for K–12 and college. Math, reading, science, SAT/ACT prep. Free intro call.",
    nearbyAreas: ["Westlake Village", "Calabasas", "Woodland Hills"],
    schools: ["Agoura High School", "Lindero Canyon Middle School"],
  },
  {
    name: "Hidden Hills",
    slug: "hidden-hills-tutoring",
    region: "Conejo Valley",
    tagline: "Private tutoring in Hidden Hills — exceptional one-on-one academic support for discerning families.",
    body: "Hidden Hills families hold their children's education to the highest standard. We bring that same rigor to every session — deep subject knowledge, a calm teaching style, and a custom plan that adapts as your student grows. No generic programs, no wasted time.",
    metaDescription: "Private tutoring in Hidden Hills, CA — elite one-on-one academic support for K–12 and college. Math, SAT/ACT prep, AP courses. First call free.",
    nearbyAreas: ["Calabasas", "Westlake Village", "Agoura Hills"],
    schools: ["Calabasas High School", "Las Virgenes Unified schools"],
  },
  // ── Glendale / Burbank / Pasadena corridor ───────────────────────────────
  {
    name: "Glendale",
    slug: "glendale-tutoring",
    region: "Los Angeles",
    tagline: "One-on-one tutoring in Glendale — personalized academic support for students who need more than a classroom can give.",
    body: "Glendale students often come from families with high academic expectations and a serious investment in their children's futures. We match that standard — working one-on-one to fill in gaps, strengthen weak subjects, and build the confidence and discipline that carry students through their most demanding years.",
    metaDescription: "Private tutoring in Glendale, CA — one-on-one academic support for K–12 and college. Math, reading, science, SAT/ACT prep. Free intro call.",
    nearbyAreas: ["Burbank", "Pasadena", "La Canada Flintridge"],
    schools: ["Hoover High School", "Glendale High School", "Clark Magnet High School", "Eleanor Roosevelt Elementary"],
  },
  {
    name: "Burbank",
    slug: "burbank-tutoring",
    region: "Los Angeles",
    tagline: "Tutoring in Burbank — steady, one-on-one support for students at every level, every subject.",
    body: "Burbank families juggle busy schedules and high expectations. We keep sessions focused and efficient — no fluff, no wasted time — so your student makes real progress without adding more stress to the week. From homework help to test prep, we work around what your household actually needs.",
    metaDescription: "Private tutoring in Burbank, CA — flexible one-on-one sessions for K–12 and college. Math, reading, science, SAT/ACT prep. Free intro call.",
    nearbyAreas: ["Glendale", "Studio City", "Pasadena"],
    schools: ["Burbank High School", "John Burroughs High School", "David Starr Jordan Middle School", "Luther Burbank Middle School"],
  },
  {
    name: "Pasadena",
    slug: "pasadena-tutoring",
    region: "San Gabriel Valley",
    tagline: "One-on-one tutoring in Pasadena — expert academic support for a diverse, academically driven community.",
    body: "Pasadena students range from public school kids navigating a heavy course load to private school students chasing competitive college admissions. We work with all of them — meeting each student at their level, filling in what's missing, and building the skills and confidence that make school feel manageable again.",
    metaDescription: "Private tutoring in Pasadena, CA — one-on-one academic support for K–12 and college. Math, reading, science, SAT/ACT prep, AP courses. Free call.",
    nearbyAreas: ["South Pasadena", "San Marino", "Glendale"],
    schools: ["Pasadena High School", "Blair International Baccalaureate", "John Muir High School", "Flintridge Prep", "Westridge School"],
  },
  {
    name: "South Pasadena",
    slug: "south-pasadena-tutoring",
    region: "San Gabriel Valley",
    tagline: "Tutoring in South Pasadena — personalized one-on-one support in one of LA's most beloved school communities.",
    body: "South Pasadena's schools are some of the most consistently high-performing in the region, which means the bar is high and slipping behind stands out. We help students stay on track or get back on track — with patient, focused sessions that target exactly what each student needs.",
    metaDescription: "Private tutoring in South Pasadena, CA — one-on-one sessions for K–12 and college. Math, reading, SAT/ACT prep, AP courses. Free intro call.",
    nearbyAreas: ["Pasadena", "San Marino", "Glendale"],
    schools: ["South Pasadena High School", "South Pasadena Middle School"],
  },
  {
    name: "San Marino",
    slug: "san-marino-tutoring",
    region: "San Gabriel Valley",
    tagline: "One-on-one tutoring in San Marino — expert academic support for one of California's most competitive school districts.",
    body: "San Marino students face significant academic pressure from an early age, and the stakes only increase through high school. We bring precision and patience to every session — clear explanations, targeted practice, and a calm approach that keeps students moving forward instead of shutting down under pressure.",
    metaDescription: "Private tutoring in San Marino, CA — expert one-on-one academic support for K–12. Math, SAT/ACT prep, AP courses, study skills. Free intro call.",
    nearbyAreas: ["Pasadena", "South Pasadena", "La Canada Flintridge"],
    schools: ["San Marino High School", "Huntington Middle School"],
  },
  {
    name: "La Canada Flintridge",
    slug: "la-canada-flintridge-tutoring",
    region: "San Gabriel Valley",
    tagline: "Private tutoring in La Canada Flintridge — rigorous one-on-one support for one of LA's most academically demanding communities.",
    body: "La Canada students are already working hard — they need targeted support, not more of the same. We specialize in helping high-achieving students close specific gaps, raise test scores, and build the organizational skills that sustain performance across a demanding course load year after year.",
    metaDescription: "Private tutoring in La Canada Flintridge, CA — expert one-on-one sessions for K–12. Math, SAT/ACT prep, AP courses, study skills. Free call.",
    nearbyAreas: ["Pasadena", "Glendale", "San Marino"],
    schools: ["La Cañada High School", "Palm Crest Elementary", "Flintridge Preparatory School", "Flintridge Sacred Heart Academy"],
  },
  // ── Westside ─────────────────────────────────────────────────────────────
  {
    name: "Beverly Hills",
    slug: "beverly-hills-tutoring",
    region: "Los Angeles (Westside)",
    tagline: "Private tutoring in Beverly Hills — rigorous support without the pressure that shuts students down.",
    body: "Beverly Hills students often face some of the most competitive academic environments in LA — GPAs matter, test scores matter, and the pressure can quietly undermine confidence. We specialize in turning that anxiety into traction: understanding the material first, building real skills second, so that grades follow naturally instead of being forced.",
    metaDescription: "Private tutoring in Beverly Hills, CA — one-on-one academic support for K–12 and college. Math, SAT/ACT prep, AP courses, study skills. First call free.",
    nearbyAreas: ["Bel Air", "West Hollywood", "Brentwood"],
    schools: ["Beverly Hills High School", "Horace Mann Middle School", "Beverly Vista Middle School", "El Rodeo Elementary", "Hawthorne Elementary"],
  },
  {
    name: "Bel Air",
    slug: "bel-air-tutoring",
    region: "Los Angeles (Westside)",
    tagline: "Private tutoring in Bel Air — personalized academic support at the level your student deserves.",
    body: "Students in Bel Air attend some of the most demanding schools in Los Angeles, public and private. We meet that bar with genuine expertise across subjects and a teaching approach that prioritizes deep understanding over short-term memorization — because the students who build real foundations are the ones who perform under pressure when it counts.",
    metaDescription: "Private tutoring in Bel Air, CA — one-on-one academic support for K–12 and college students. Math, SAT/ACT prep, AP courses, study skills. Free call.",
    nearbyAreas: ["Beverly Hills", "Holmby Hills", "Brentwood"],
    schools: ["Paul Revere Middle School", "Bel Air Elementary", "Westlake School"],
  },
  {
    name: "Holmby Hills",
    slug: "holmby-hills-tutoring",
    region: "Los Angeles (Westside)",
    tagline: "Private tutoring in Holmby Hills — exceptional one-on-one academic support for families who demand the best.",
    body: "Holmby Hills families expect a standard of excellence in everything — and academic support is no exception. We bring that same level of commitment to every session: genuine subject expertise, a customized plan, and the patience to make sure your student truly understands, not just gets through.",
    metaDescription: "Private tutoring in Holmby Hills, CA — premium one-on-one academic support for K–12 and college. Math, SAT/ACT prep, AP courses. First call free.",
    nearbyAreas: ["Beverly Hills", "Bel Air", "Brentwood"],
    schools: ["Fairburn Elementary", "Westwood Charter", "Paul Revere Middle School"],
  },
  {
    name: "Brentwood",
    slug: "brentwood-tutoring",
    region: "Los Angeles (Westside)",
    tagline: "One-on-one tutoring in Brentwood — personalized academic support on the westside.",
    body: "Brentwood students attend some of LA's most competitive public and private schools, where expectations are high and the pace is fast. We help students stay ahead of that pace — or get back to it — with focused one-on-one sessions that build genuine understanding, not just short-term exam performance.",
    metaDescription: "Private tutoring in Brentwood, CA — one-on-one sessions for K–12 and college. Math, reading, SAT/ACT prep, AP courses, study skills. Free intro call.",
    nearbyAreas: ["Pacific Palisades", "Santa Monica", "Bel Air"],
    schools: ["Brentwood School", "Kenter Canyon Elementary", "Paul Revere Middle School"],
  },
  {
    name: "Pacific Palisades",
    slug: "pacific-palisades-tutoring",
    region: "Los Angeles (Westside)",
    tagline: "Private tutoring in Pacific Palisades — rigorous academic support for one of LA's most demanding school communities.",
    body: "Pacific Palisades students face a competitive academic environment where strong grades, high test scores, and a full activities schedule are all expected at once. We bring calm, focused one-on-one support that helps students manage that pressure — building genuine skill rather than just grinding through another test.",
    metaDescription: "Private tutoring in Pacific Palisades, CA — one-on-one support for K–12 and college. Math, SAT/ACT prep, AP courses, study skills. First call free.",
    nearbyAreas: ["Brentwood", "Santa Monica", "Bel Air"],
    schools: ["Palisades Charter High School", "Marquez Charter", "Palisades Elementary"],
  },
  {
    name: "Santa Monica",
    slug: "santa-monica-tutoring",
    region: "Los Angeles (Westside)",
    tagline: "Private tutoring in Santa Monica — rigorous academic support that keeps pace with the westside's high standards.",
    body: "Santa Monica students compete in some of the most academically demanding environments on the westside. Whether it's honors and AP coursework, standardized test preparation, or college-level work, we bring the patience and subject-matter depth to help students perform — and stop dreading school.",
    metaDescription: "Private tutoring in Santa Monica, CA — one-on-one academic support for K–12 and college. SAT/ACT prep, AP courses, study skills. First call free.",
    nearbyAreas: ["Brentwood", "Pacific Palisades", "Marina del Rey"],
    schools: ["Santa Monica High School", "John Adams Middle School", "Lincoln Middle School", "Crossroads School", "Saint Monica Catholic High"],
  },
  {
    name: "West Hollywood",
    slug: "west-hollywood-tutoring",
    region: "Los Angeles (Westside)",
    tagline: "One-on-one tutoring in West Hollywood — patient, personalized support for every kind of learner.",
    body: "West Hollywood students come from diverse backgrounds and learn in different ways. We meet every student where they are — whether they need to close a gap, tackle a challenging course load, or build the habits and confidence that make school feel less overwhelming. All one-on-one, all built around how your student actually learns.",
    metaDescription: "Private tutoring in West Hollywood, CA — one-on-one sessions for K–12 and college. Math, reading, science, SAT/ACT prep, ADHD-friendly. Free intro call.",
    nearbyAreas: ["Beverly Hills", "Studio City", "Los Angeles"],
    schools: ["Fairfax High School", "West Hollywood Elementary", "Laurel Elementary"],
  },
  {
    name: "Marina del Rey",
    slug: "marina-del-rey-tutoring",
    region: "Los Angeles (Westside)",
    tagline: "One-on-one tutoring in Marina del Rey — personalized sessions for students who need focused, patient support.",
    body: "Families in Marina del Rey expect a high standard of academic support — and that's exactly what we deliver. Every session is one-on-one and built around your student's actual schedule, learning style, and specific gaps. No cookie-cutter plans, no wasted hours.",
    metaDescription: "Private tutoring in Marina del Rey, CA — one-on-one sessions for K–12 and college. Math, reading, SAT/ACT prep, study skills. First call free.",
    nearbyAreas: ["Santa Monica", "Culver City", "Brentwood"],
    schools: ["Coeur d'Alene Elementary", "Del Rey Heights Elementary"],
  },
  {
    name: "Culver City",
    slug: "culver-city-tutoring",
    region: "Los Angeles (Westside)",
    tagline: "One-on-one tutoring in Culver City — personalized academic support in one of LA's fastest-growing communities.",
    body: "Culver City students attend strong public schools where parental expectations are high and the student body is competitive. We help students at every level — from kids who need a confidence boost to high schoolers building toward demanding college applications — with patient, structured sessions tailored to how they actually learn.",
    metaDescription: "Private tutoring in Culver City, CA — one-on-one sessions for K–12 and college. Math, reading, science, SAT/ACT prep. Free intro call.",
    nearbyAreas: ["Santa Monica", "Marina del Rey", "Brentwood"],
    schools: ["Culver City High School", "El Rincon Elementary", "Farragut Elementary"],
  },
  {
    name: "Los Angeles",
    slug: "los-angeles-tutoring",
    region: "Los Angeles",
    tagline: "One-on-one tutoring across Los Angeles — covering every neighborhood, every subject, every grade level.",
    body: "HUMBLE Learning Co. serves students across Los Angeles — from the San Fernando Valley to the Westside, Beverly Hills to Pasadena. Whether your student needs math support, reading help, SAT prep, or someone to build executive function skills alongside them, we offer flexible in-person and online sessions built around your schedule.",
    metaDescription: "Private tutoring in Los Angeles, CA — one-on-one sessions for K–12 and college. Math, reading, science, SAT/ACT prep, ADHD-friendly support. Free intro call.",
    nearbyAreas: ["Beverly Hills", "Culver City", "Santa Monica"],
    schools: [],
  },
  // ── South Bay ────────────────────────────────────────────────────────────
  {
    name: "Manhattan Beach",
    slug: "manhattan-beach-tutoring",
    region: "South Bay",
    tagline: "One-on-one tutoring in Manhattan Beach — excellent academic support for a community that takes education seriously.",
    body: "Manhattan Beach families combine high incomes with high educational expectations — their students attend some of the best public schools in the South Bay, and falling behind stands out. We work one-on-one to close gaps, strengthen weak subjects, and build the study skills that keep students performing at the level their school demands.",
    metaDescription: "Private tutoring in Manhattan Beach, CA — one-on-one sessions for K–12 and college. Math, reading, SAT/ACT prep, AP courses. Free intro call.",
    nearbyAreas: ["Hermosa Beach", "Redondo Beach", "Palos Verdes Estates"],
    schools: ["Mira Costa High School", "Manhattan Beach Middle School", "Meadows Elementary"],
  },
  {
    name: "Redondo Beach",
    slug: "redondo-beach-tutoring",
    region: "South Bay",
    tagline: "Tutoring in Redondo Beach — flexible, one-on-one academic support for South Bay families.",
    body: "Redondo Beach students come from families who care about real academic progress, not just grades on a report card. We work with students at every level — building foundational skills, tackling honors coursework, or preparing for standardized tests — with a patient, focused approach that produces lasting results.",
    metaDescription: "Private tutoring in Redondo Beach, CA — one-on-one sessions for K–12 and college. Math, reading, science, SAT/ACT prep. Free intro call.",
    nearbyAreas: ["Hermosa Beach", "Manhattan Beach", "Rancho Palos Verdes"],
    schools: ["Redondo Union High School", "Adams Middle School", "Washington Elementary"],
  },
  {
    name: "Hermosa Beach",
    slug: "hermosa-beach-tutoring",
    region: "South Bay",
    tagline: "One-on-one tutoring in Hermosa Beach — personalized academic support for South Bay students.",
    body: "Hermosa Beach students thrive in a community that values both quality of life and academic achievement. We support that balance — providing focused, one-on-one sessions that help students stay on track without turning homework into a second full-time job.",
    metaDescription: "Private tutoring in Hermosa Beach, CA — one-on-one sessions for K–12 and college. Math, reading, SAT/ACT prep, study skills. Free intro call.",
    nearbyAreas: ["Manhattan Beach", "Redondo Beach", "Rancho Palos Verdes"],
    schools: ["Hermosa Valley Elementary", "Hermosa View Elementary", "Mira Costa High School"],
  },
  {
    name: "Palos Verdes Estates",
    slug: "palos-verdes-estates-tutoring",
    region: "South Bay",
    tagline: "Private tutoring in Palos Verdes Estates — rigorous academic support for the Peninsula's highest-achieving students.",
    body: "Palos Verdes students attend some of the most academically competitive schools in Southern California. We bring precision and patience to every session — working one-on-one to build the kind of deep understanding that holds up under the pressure of honors courses, AP exams, and college admissions testing.",
    metaDescription: "Private tutoring in Palos Verdes Estates, CA — expert one-on-one sessions for K–12 and college. Math, SAT/ACT prep, AP courses. Free intro call.",
    nearbyAreas: ["Rancho Palos Verdes", "Rolling Hills", "Manhattan Beach"],
    schools: ["Palos Verdes Peninsula High School", "Malaga Cove Middle School", "Lunada Bay Elementary"],
  },
  {
    name: "Rancho Palos Verdes",
    slug: "rancho-palos-verdes-tutoring",
    region: "South Bay",
    tagline: "One-on-one tutoring in Rancho Palos Verdes — expert academic support for Peninsula families.",
    body: "Rancho Palos Verdes students face a demanding academic environment where the expectations are high and the competition is real. We work one-on-one to help students understand the material deeply — not just pass the next test — and build the habits and skills that sustain performance across every subject.",
    metaDescription: "Private tutoring in Rancho Palos Verdes, CA — one-on-one sessions for K–12 and college. Math, SAT/ACT prep, AP courses, study skills. Free call.",
    nearbyAreas: ["Palos Verdes Estates", "Rolling Hills", "Redondo Beach"],
    schools: ["Palos Verdes Peninsula High School", "Miraleste Intermediate"],
  },
  {
    name: "Rolling Hills",
    slug: "rolling-hills-tutoring",
    region: "South Bay",
    tagline: "Private tutoring in Rolling Hills — exceptional one-on-one academic support for Peninsula families.",
    body: "Rolling Hills is one of the most exclusive communities in Southern California, and the families here expect academic support that matches that standard. Every session is one-on-one, every plan is custom, and every student receives the patient, expert instruction that translates into genuine, lasting improvement.",
    metaDescription: "Private tutoring in Rolling Hills, CA — premium one-on-one academic support for K–12 and college. Math, SAT/ACT prep, AP courses. First call free.",
    nearbyAreas: ["Palos Verdes Estates", "Rancho Palos Verdes", "Manhattan Beach"],
    schools: ["Palos Verdes Peninsula High School", "Rolling Hills Elementary"],
  },
];

export function getNeighborhood(slug: string): Neighborhood | undefined {
  return neighborhoods.find((n) => n.slug === slug);
}
